application: my-radar
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: my-radar.app

libraries:
- name: jinja2
  version: latest